'use client';

import { db } from '@/lib/firebase'; // your firebase config
import { collection, getDocs } from 'firebase/firestore';
import { useEffect, useState } from 'react';
import HeaderAndSearch from '../_components/HeaderAndSearch';
import ReportsTable from '../_components/ReportsTable';
import { Report } from '@/types/reports';
import { exportAllReportsToPDF } from '@/utils/exportAllReportsToPDF';

const Reports = () => {
    const [reports, setReports] = useState<Report[]>([]);
    const [loading, setLoading] = useState(true);
    const [searchTerm, setSearchTerm] = useState('');

    useEffect(() => {
        const fetchReports = async () => {
            try {
                const snapshot = await getDocs(collection(db, 'reports'));
                const data = snapshot.docs.map((doc) => {
                    const d = doc.data();
                    return {
                        id: doc.id,
                        title: d.title,
                        reportedBy: d.reportedBy,
                        reason: d.reason,
                        reportedAt: d.reportedAt
                            ? d.reportedAt.toDate().toLocaleString()
                            : '',
                    };
                }) as Report[];

                setReports(data);
            } catch (error) {
                console.error('Error fetching reports:', error);
            } finally {
                setLoading(false);
            }
        };

        fetchReports();
    }, []);

    const handleExportPDF = () => {
        exportAllReportsToPDF(reports, {
            fileName: 'reports.pdf',
            title: 'All Reports',
            subtitle: 'Generated by CheFu Academy Admin Panel',
            logoUrl: '/logo.png', // Optional – local/public image or base64 data URL
        });
    };

    return (
        <div className=" md:p-6">
            <HeaderAndSearch
                searchTerm={searchTerm}
                setSearchTerm={setSearchTerm}
                handleExportPDF={handleExportPDF}
            />

            {/* Reports Table */}
            <ReportsTable reports={reports} loading={loading} />
        </div>
    );
};

export default Reports;
